// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/nicholas-fedor/speedtest-go/speedtest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// AddTotalDownload provides a mock function for the type MockManager
func (_mock *MockManager) AddTotalDownload(value int64) {
	_mock.Called(value)
	return
}

// MockManager_AddTotalDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTotalDownload'
type MockManager_AddTotalDownload_Call struct {
	*mock.Call
}

// AddTotalDownload is a helper method to define mock.On call
//   - value int64
func (_e *MockManager_Expecter) AddTotalDownload(value interface{}) *MockManager_AddTotalDownload_Call {
	return &MockManager_AddTotalDownload_Call{Call: _e.mock.On("AddTotalDownload", value)}
}

func (_c *MockManager_AddTotalDownload_Call) Run(run func(value int64)) *MockManager_AddTotalDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_AddTotalDownload_Call) Return() *MockManager_AddTotalDownload_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_AddTotalDownload_Call) RunAndReturn(run func(value int64)) *MockManager_AddTotalDownload_Call {
	_c.Run(run)
	return _c
}

// AddTotalUpload provides a mock function for the type MockManager
func (_mock *MockManager) AddTotalUpload(value int64) {
	_mock.Called(value)
	return
}

// MockManager_AddTotalUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTotalUpload'
type MockManager_AddTotalUpload_Call struct {
	*mock.Call
}

// AddTotalUpload is a helper method to define mock.On call
//   - value int64
func (_e *MockManager_Expecter) AddTotalUpload(value interface{}) *MockManager_AddTotalUpload_Call {
	return &MockManager_AddTotalUpload_Call{Call: _e.mock.On("AddTotalUpload", value)}
}

func (_c *MockManager_AddTotalUpload_Call) Run(run func(value int64)) *MockManager_AddTotalUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_AddTotalUpload_Call) Return() *MockManager_AddTotalUpload_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_AddTotalUpload_Call) RunAndReturn(run func(value int64)) *MockManager_AddTotalUpload_Call {
	_c.Run(run)
	return _c
}

// GetAvgDownloadRate provides a mock function for the type MockManager
func (_mock *MockManager) GetAvgDownloadRate() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAvgDownloadRate")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockManager_GetAvgDownloadRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvgDownloadRate'
type MockManager_GetAvgDownloadRate_Call struct {
	*mock.Call
}

// GetAvgDownloadRate is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetAvgDownloadRate() *MockManager_GetAvgDownloadRate_Call {
	return &MockManager_GetAvgDownloadRate_Call{Call: _e.mock.On("GetAvgDownloadRate")}
}

func (_c *MockManager_GetAvgDownloadRate_Call) Run(run func()) *MockManager_GetAvgDownloadRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetAvgDownloadRate_Call) Return(f float64) *MockManager_GetAvgDownloadRate_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockManager_GetAvgDownloadRate_Call) RunAndReturn(run func() float64) *MockManager_GetAvgDownloadRate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvgUploadRate provides a mock function for the type MockManager
func (_mock *MockManager) GetAvgUploadRate() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAvgUploadRate")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockManager_GetAvgUploadRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvgUploadRate'
type MockManager_GetAvgUploadRate_Call struct {
	*mock.Call
}

// GetAvgUploadRate is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetAvgUploadRate() *MockManager_GetAvgUploadRate_Call {
	return &MockManager_GetAvgUploadRate_Call{Call: _e.mock.On("GetAvgUploadRate")}
}

func (_c *MockManager_GetAvgUploadRate_Call) Run(run func()) *MockManager_GetAvgUploadRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetAvgUploadRate_Call) Return(f float64) *MockManager_GetAvgUploadRate_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockManager_GetAvgUploadRate_Call) RunAndReturn(run func() float64) *MockManager_GetAvgUploadRate_Call {
	_c.Call.Return(run)
	return _c
}

// GetEWMADownloadRate provides a mock function for the type MockManager
func (_mock *MockManager) GetEWMADownloadRate() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEWMADownloadRate")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockManager_GetEWMADownloadRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEWMADownloadRate'
type MockManager_GetEWMADownloadRate_Call struct {
	*mock.Call
}

// GetEWMADownloadRate is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetEWMADownloadRate() *MockManager_GetEWMADownloadRate_Call {
	return &MockManager_GetEWMADownloadRate_Call{Call: _e.mock.On("GetEWMADownloadRate")}
}

func (_c *MockManager_GetEWMADownloadRate_Call) Run(run func()) *MockManager_GetEWMADownloadRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetEWMADownloadRate_Call) Return(f float64) *MockManager_GetEWMADownloadRate_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockManager_GetEWMADownloadRate_Call) RunAndReturn(run func() float64) *MockManager_GetEWMADownloadRate_Call {
	_c.Call.Return(run)
	return _c
}

// GetEWMAUploadRate provides a mock function for the type MockManager
func (_mock *MockManager) GetEWMAUploadRate() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEWMAUploadRate")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockManager_GetEWMAUploadRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEWMAUploadRate'
type MockManager_GetEWMAUploadRate_Call struct {
	*mock.Call
}

// GetEWMAUploadRate is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetEWMAUploadRate() *MockManager_GetEWMAUploadRate_Call {
	return &MockManager_GetEWMAUploadRate_Call{Call: _e.mock.On("GetEWMAUploadRate")}
}

func (_c *MockManager_GetEWMAUploadRate_Call) Run(run func()) *MockManager_GetEWMAUploadRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetEWMAUploadRate_Call) Return(f float64) *MockManager_GetEWMAUploadRate_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockManager_GetEWMAUploadRate_Call) RunAndReturn(run func() float64) *MockManager_GetEWMAUploadRate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalDownload provides a mock function for the type MockManager
func (_mock *MockManager) GetTotalDownload() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTotalDownload")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockManager_GetTotalDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalDownload'
type MockManager_GetTotalDownload_Call struct {
	*mock.Call
}

// GetTotalDownload is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetTotalDownload() *MockManager_GetTotalDownload_Call {
	return &MockManager_GetTotalDownload_Call{Call: _e.mock.On("GetTotalDownload")}
}

func (_c *MockManager_GetTotalDownload_Call) Run(run func()) *MockManager_GetTotalDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetTotalDownload_Call) Return(n int64) *MockManager_GetTotalDownload_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockManager_GetTotalDownload_Call) RunAndReturn(run func() int64) *MockManager_GetTotalDownload_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalUpload provides a mock function for the type MockManager
func (_mock *MockManager) GetTotalUpload() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTotalUpload")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockManager_GetTotalUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalUpload'
type MockManager_GetTotalUpload_Call struct {
	*mock.Call
}

// GetTotalUpload is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetTotalUpload() *MockManager_GetTotalUpload_Call {
	return &MockManager_GetTotalUpload_Call{Call: _e.mock.On("GetTotalUpload")}
}

func (_c *MockManager_GetTotalUpload_Call) Run(run func()) *MockManager_GetTotalUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetTotalUpload_Call) Return(n int64) *MockManager_GetTotalUpload_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockManager_GetTotalUpload_Call) RunAndReturn(run func() int64) *MockManager_GetTotalUpload_Call {
	_c.Call.Return(run)
	return _c
}

// NewChunk provides a mock function for the type MockManager
func (_mock *MockManager) NewChunk() speedtest.Chunk {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewChunk")
	}

	var r0 speedtest.Chunk
	if returnFunc, ok := ret.Get(0).(func() speedtest.Chunk); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(speedtest.Chunk)
		}
	}
	return r0
}

// MockManager_NewChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewChunk'
type MockManager_NewChunk_Call struct {
	*mock.Call
}

// NewChunk is a helper method to define mock.On call
func (_e *MockManager_Expecter) NewChunk() *MockManager_NewChunk_Call {
	return &MockManager_NewChunk_Call{Call: _e.mock.On("NewChunk")}
}

func (_c *MockManager_NewChunk_Call) Run(run func()) *MockManager_NewChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_NewChunk_Call) Return(chunk speedtest.Chunk) *MockManager_NewChunk_Call {
	_c.Call.Return(chunk)
	return _c
}

func (_c *MockManager_NewChunk_Call) RunAndReturn(run func() speedtest.Chunk) *MockManager_NewChunk_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterDownloadHandler provides a mock function for the type MockManager
func (_mock *MockManager) RegisterDownloadHandler(fn func()) *speedtest.TestDirection {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDownloadHandler")
	}

	var r0 *speedtest.TestDirection
	if returnFunc, ok := ret.Get(0).(func(func()) *speedtest.TestDirection); ok {
		r0 = returnFunc(fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*speedtest.TestDirection)
		}
	}
	return r0
}

// MockManager_RegisterDownloadHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDownloadHandler'
type MockManager_RegisterDownloadHandler_Call struct {
	*mock.Call
}

// RegisterDownloadHandler is a helper method to define mock.On call
//   - fn func()
func (_e *MockManager_Expecter) RegisterDownloadHandler(fn interface{}) *MockManager_RegisterDownloadHandler_Call {
	return &MockManager_RegisterDownloadHandler_Call{Call: _e.mock.On("RegisterDownloadHandler", fn)}
}

func (_c *MockManager_RegisterDownloadHandler_Call) Run(run func(fn func())) *MockManager_RegisterDownloadHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_RegisterDownloadHandler_Call) Return(testDirection *speedtest.TestDirection) *MockManager_RegisterDownloadHandler_Call {
	_c.Call.Return(testDirection)
	return _c
}

func (_c *MockManager_RegisterDownloadHandler_Call) RunAndReturn(run func(fn func()) *speedtest.TestDirection) *MockManager_RegisterDownloadHandler_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUploadHandler provides a mock function for the type MockManager
func (_mock *MockManager) RegisterUploadHandler(fn func()) *speedtest.TestDirection {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUploadHandler")
	}

	var r0 *speedtest.TestDirection
	if returnFunc, ok := ret.Get(0).(func(func()) *speedtest.TestDirection); ok {
		r0 = returnFunc(fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*speedtest.TestDirection)
		}
	}
	return r0
}

// MockManager_RegisterUploadHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUploadHandler'
type MockManager_RegisterUploadHandler_Call struct {
	*mock.Call
}

// RegisterUploadHandler is a helper method to define mock.On call
//   - fn func()
func (_e *MockManager_Expecter) RegisterUploadHandler(fn interface{}) *MockManager_RegisterUploadHandler_Call {
	return &MockManager_RegisterUploadHandler_Call{Call: _e.mock.On("RegisterUploadHandler", fn)}
}

func (_c *MockManager_RegisterUploadHandler_Call) Run(run func(fn func())) *MockManager_RegisterUploadHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_RegisterUploadHandler_Call) Return(testDirection *speedtest.TestDirection) *MockManager_RegisterUploadHandler_Call {
	_c.Call.Return(testDirection)
	return _c
}

func (_c *MockManager_RegisterUploadHandler_Call) RunAndReturn(run func(fn func()) *speedtest.TestDirection) *MockManager_RegisterUploadHandler_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type MockManager
func (_mock *MockManager) Reset() {
	_mock.Called()
	return
}

// MockManager_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockManager_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *MockManager_Expecter) Reset() *MockManager_Reset_Call {
	return &MockManager_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *MockManager_Reset_Call) Run(run func()) *MockManager_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Reset_Call) Return() *MockManager_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Reset_Call) RunAndReturn(run func()) *MockManager_Reset_Call {
	_c.Run(run)
	return _c
}

// SetCallbackDownload provides a mock function for the type MockManager
func (_mock *MockManager) SetCallbackDownload(callback func(downRate speedtest.ByteRate)) {
	_mock.Called(callback)
	return
}

// MockManager_SetCallbackDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCallbackDownload'
type MockManager_SetCallbackDownload_Call struct {
	*mock.Call
}

// SetCallbackDownload is a helper method to define mock.On call
//   - callback func(downRate speedtest.ByteRate)
func (_e *MockManager_Expecter) SetCallbackDownload(callback interface{}) *MockManager_SetCallbackDownload_Call {
	return &MockManager_SetCallbackDownload_Call{Call: _e.mock.On("SetCallbackDownload", callback)}
}

func (_c *MockManager_SetCallbackDownload_Call) Run(run func(callback func(downRate speedtest.ByteRate))) *MockManager_SetCallbackDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(downRate speedtest.ByteRate)
		if args[0] != nil {
			arg0 = args[0].(func(downRate speedtest.ByteRate))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetCallbackDownload_Call) Return() *MockManager_SetCallbackDownload_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_SetCallbackDownload_Call) RunAndReturn(run func(callback func(downRate speedtest.ByteRate))) *MockManager_SetCallbackDownload_Call {
	_c.Run(run)
	return _c
}

// SetCallbackUpload provides a mock function for the type MockManager
func (_mock *MockManager) SetCallbackUpload(callback func(upRate speedtest.ByteRate)) {
	_mock.Called(callback)
	return
}

// MockManager_SetCallbackUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCallbackUpload'
type MockManager_SetCallbackUpload_Call struct {
	*mock.Call
}

// SetCallbackUpload is a helper method to define mock.On call
//   - callback func(upRate speedtest.ByteRate)
func (_e *MockManager_Expecter) SetCallbackUpload(callback interface{}) *MockManager_SetCallbackUpload_Call {
	return &MockManager_SetCallbackUpload_Call{Call: _e.mock.On("SetCallbackUpload", callback)}
}

func (_c *MockManager_SetCallbackUpload_Call) Run(run func(callback func(upRate speedtest.ByteRate))) *MockManager_SetCallbackUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(upRate speedtest.ByteRate)
		if args[0] != nil {
			arg0 = args[0].(func(upRate speedtest.ByteRate))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetCallbackUpload_Call) Return() *MockManager_SetCallbackUpload_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_SetCallbackUpload_Call) RunAndReturn(run func(callback func(upRate speedtest.ByteRate))) *MockManager_SetCallbackUpload_Call {
	_c.Run(run)
	return _c
}

// SetCaptureTime provides a mock function for the type MockManager
func (_mock *MockManager) SetCaptureTime(duration time.Duration) speedtest.Manager {
	ret := _mock.Called(duration)

	if len(ret) == 0 {
		panic("no return value specified for SetCaptureTime")
	}

	var r0 speedtest.Manager
	if returnFunc, ok := ret.Get(0).(func(time.Duration) speedtest.Manager); ok {
		r0 = returnFunc(duration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(speedtest.Manager)
		}
	}
	return r0
}

// MockManager_SetCaptureTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCaptureTime'
type MockManager_SetCaptureTime_Call struct {
	*mock.Call
}

// SetCaptureTime is a helper method to define mock.On call
//   - duration time.Duration
func (_e *MockManager_Expecter) SetCaptureTime(duration interface{}) *MockManager_SetCaptureTime_Call {
	return &MockManager_SetCaptureTime_Call{Call: _e.mock.On("SetCaptureTime", duration)}
}

func (_c *MockManager_SetCaptureTime_Call) Run(run func(duration time.Duration)) *MockManager_SetCaptureTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetCaptureTime_Call) Return(manager speedtest.Manager) *MockManager_SetCaptureTime_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetCaptureTime_Call) RunAndReturn(run func(duration time.Duration) speedtest.Manager) *MockManager_SetCaptureTime_Call {
	_c.Call.Return(run)
	return _c
}

// SetNThread provides a mock function for the type MockManager
func (_mock *MockManager) SetNThread(n int) speedtest.Manager {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for SetNThread")
	}

	var r0 speedtest.Manager
	if returnFunc, ok := ret.Get(0).(func(int) speedtest.Manager); ok {
		r0 = returnFunc(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(speedtest.Manager)
		}
	}
	return r0
}

// MockManager_SetNThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNThread'
type MockManager_SetNThread_Call struct {
	*mock.Call
}

// SetNThread is a helper method to define mock.On call
//   - n int
func (_e *MockManager_Expecter) SetNThread(n interface{}) *MockManager_SetNThread_Call {
	return &MockManager_SetNThread_Call{Call: _e.mock.On("SetNThread", n)}
}

func (_c *MockManager_SetNThread_Call) Run(run func(n int)) *MockManager_SetNThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetNThread_Call) Return(manager speedtest.Manager) *MockManager_SetNThread_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetNThread_Call) RunAndReturn(run func(n int) speedtest.Manager) *MockManager_SetNThread_Call {
	_c.Call.Return(run)
	return _c
}

// SetRateCaptureFrequency provides a mock function for the type MockManager
func (_mock *MockManager) SetRateCaptureFrequency(duration time.Duration) speedtest.Manager {
	ret := _mock.Called(duration)

	if len(ret) == 0 {
		panic("no return value specified for SetRateCaptureFrequency")
	}

	var r0 speedtest.Manager
	if returnFunc, ok := ret.Get(0).(func(time.Duration) speedtest.Manager); ok {
		r0 = returnFunc(duration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(speedtest.Manager)
		}
	}
	return r0
}

// MockManager_SetRateCaptureFrequency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRateCaptureFrequency'
type MockManager_SetRateCaptureFrequency_Call struct {
	*mock.Call
}

// SetRateCaptureFrequency is a helper method to define mock.On call
//   - duration time.Duration
func (_e *MockManager_Expecter) SetRateCaptureFrequency(duration interface{}) *MockManager_SetRateCaptureFrequency_Call {
	return &MockManager_SetRateCaptureFrequency_Call{Call: _e.mock.On("SetRateCaptureFrequency", duration)}
}

func (_c *MockManager_SetRateCaptureFrequency_Call) Run(run func(duration time.Duration)) *MockManager_SetRateCaptureFrequency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetRateCaptureFrequency_Call) Return(manager speedtest.Manager) *MockManager_SetRateCaptureFrequency_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetRateCaptureFrequency_Call) RunAndReturn(run func(duration time.Duration) speedtest.Manager) *MockManager_SetRateCaptureFrequency_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshots provides a mock function for the type MockManager
func (_mock *MockManager) Snapshots() *speedtest.Snapshots {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshots")
	}

	var r0 *speedtest.Snapshots
	if returnFunc, ok := ret.Get(0).(func() *speedtest.Snapshots); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*speedtest.Snapshots)
		}
	}
	return r0
}

// MockManager_Snapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshots'
type MockManager_Snapshots_Call struct {
	*mock.Call
}

// Snapshots is a helper method to define mock.On call
func (_e *MockManager_Expecter) Snapshots() *MockManager_Snapshots_Call {
	return &MockManager_Snapshots_Call{Call: _e.mock.On("Snapshots")}
}

func (_c *MockManager_Snapshots_Call) Run(run func()) *MockManager_Snapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Snapshots_Call) Return(snapshots *speedtest.Snapshots) *MockManager_Snapshots_Call {
	_c.Call.Return(snapshots)
	return _c
}

func (_c *MockManager_Snapshots_Call) RunAndReturn(run func() *speedtest.Snapshots) *MockManager_Snapshots_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockManager
func (_mock *MockManager) Wait() {
	_mock.Called()
	return
}

// MockManager_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockManager_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockManager_Expecter) Wait() *MockManager_Wait_Call {
	return &MockManager_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockManager_Wait_Call) Run(run func()) *MockManager_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Wait_Call) Return() *MockManager_Wait_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Wait_Call) RunAndReturn(run func()) *MockManager_Wait_Call {
	_c.Run(run)
	return _c
}
