// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"
	"time"

	"github.com/showwin/speedtest-go/speedtest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChunk creates a new instance of MockChunk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunk(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunk {
	mock := &MockChunk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChunk is an autogenerated mock type for the Chunk type
type MockChunk struct {
	mock.Mock
}

type MockChunk_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunk) EXPECT() *MockChunk_Expecter {
	return &MockChunk_Expecter{mock: &_m.Mock}
}

// DownloadHandler provides a mock function for the type MockChunk
func (_mock *MockChunk) DownloadHandler(r io.Reader) error {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for DownloadHandler")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChunk_DownloadHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadHandler'
type MockChunk_DownloadHandler_Call struct {
	*mock.Call
}

// DownloadHandler is a helper method to define mock.On call
//   - r io.Reader
func (_e *MockChunk_Expecter) DownloadHandler(r interface{}) *MockChunk_DownloadHandler_Call {
	return &MockChunk_DownloadHandler_Call{Call: _e.mock.On("DownloadHandler", r)}
}

func (_c *MockChunk_DownloadHandler_Call) Run(run func(r io.Reader)) *MockChunk_DownloadHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChunk_DownloadHandler_Call) Return(err error) *MockChunk_DownloadHandler_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChunk_DownloadHandler_Call) RunAndReturn(run func(r io.Reader) error) *MockChunk_DownloadHandler_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuration provides a mock function for the type MockChunk
func (_mock *MockChunk) GetDuration() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDuration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockChunk_GetDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuration'
type MockChunk_GetDuration_Call struct {
	*mock.Call
}

// GetDuration is a helper method to define mock.On call
func (_e *MockChunk_Expecter) GetDuration() *MockChunk_GetDuration_Call {
	return &MockChunk_GetDuration_Call{Call: _e.mock.On("GetDuration")}
}

func (_c *MockChunk_GetDuration_Call) Run(run func()) *MockChunk_GetDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChunk_GetDuration_Call) Return(duration time.Duration) *MockChunk_GetDuration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockChunk_GetDuration_Call) RunAndReturn(run func() time.Duration) *MockChunk_GetDuration_Call {
	_c.Call.Return(run)
	return _c
}

// GetParent provides a mock function for the type MockChunk
func (_mock *MockChunk) GetParent() speedtest.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParent")
	}

	var r0 speedtest.Manager
	if returnFunc, ok := ret.Get(0).(func() speedtest.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(speedtest.Manager)
		}
	}
	return r0
}

// MockChunk_GetParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParent'
type MockChunk_GetParent_Call struct {
	*mock.Call
}

// GetParent is a helper method to define mock.On call
func (_e *MockChunk_Expecter) GetParent() *MockChunk_GetParent_Call {
	return &MockChunk_GetParent_Call{Call: _e.mock.On("GetParent")}
}

func (_c *MockChunk_GetParent_Call) Run(run func()) *MockChunk_GetParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChunk_GetParent_Call) Return(manager speedtest.Manager) *MockChunk_GetParent_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockChunk_GetParent_Call) RunAndReturn(run func() speedtest.Manager) *MockChunk_GetParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetRate provides a mock function for the type MockChunk
func (_mock *MockChunk) GetRate() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRate")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockChunk_GetRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRate'
type MockChunk_GetRate_Call struct {
	*mock.Call
}

// GetRate is a helper method to define mock.On call
func (_e *MockChunk_Expecter) GetRate() *MockChunk_GetRate_Call {
	return &MockChunk_GetRate_Call{Call: _e.mock.On("GetRate")}
}

func (_c *MockChunk_GetRate_Call) Run(run func()) *MockChunk_GetRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChunk_GetRate_Call) Return(f float64) *MockChunk_GetRate_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockChunk_GetRate_Call) RunAndReturn(run func() float64) *MockChunk_GetRate_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockChunk
func (_mock *MockChunk) Read(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChunk_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockChunk_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - b []byte
func (_e *MockChunk_Expecter) Read(b interface{}) *MockChunk_Read_Call {
	return &MockChunk_Read_Call{Call: _e.mock.On("Read", b)}
}

func (_c *MockChunk_Read_Call) Run(run func(b []byte)) *MockChunk_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChunk_Read_Call) Return(n int, err error) *MockChunk_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockChunk_Read_Call) RunAndReturn(run func(b []byte) (int, error)) *MockChunk_Read_Call {
	_c.Call.Return(run)
	return _c
}

// UploadHandler provides a mock function for the type MockChunk
func (_mock *MockChunk) UploadHandler(size int64) speedtest.Chunk {
	ret := _mock.Called(size)

	if len(ret) == 0 {
		panic("no return value specified for UploadHandler")
	}

	var r0 speedtest.Chunk
	if returnFunc, ok := ret.Get(0).(func(int64) speedtest.Chunk); ok {
		r0 = returnFunc(size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(speedtest.Chunk)
		}
	}
	return r0
}

// MockChunk_UploadHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadHandler'
type MockChunk_UploadHandler_Call struct {
	*mock.Call
}

// UploadHandler is a helper method to define mock.On call
//   - size int64
func (_e *MockChunk_Expecter) UploadHandler(size interface{}) *MockChunk_UploadHandler_Call {
	return &MockChunk_UploadHandler_Call{Call: _e.mock.On("UploadHandler", size)}
}

func (_c *MockChunk_UploadHandler_Call) Run(run func(size int64)) *MockChunk_UploadHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChunk_UploadHandler_Call) Return(chunk speedtest.Chunk) *MockChunk_UploadHandler_Call {
	_c.Call.Return(chunk)
	return _c
}

func (_c *MockChunk_UploadHandler_Call) RunAndReturn(run func(size int64) speedtest.Chunk) *MockChunk_UploadHandler_Call {
	_c.Call.Return(run)
	return _c
}
